In [184]:
import pandas as pd
import calendar as c
c.setfirstweekday(calendar.SUNDAY)

In [24]:
start='2022-03-01'
end='2022-04-30'

In [190]:
df = pd.DataFrame({"Date": pd.date_range(start, end)})
df['DateCK'] = df.Date.dt.year.astype(str) + df.Date.dt.month.astype(str).str.zfill(2) + df.Date.dt.day.astype(str).str.zfill(2)
df['FormattedDate'] = df.Date.dt.strftime('%m/%d/%Y')
df['DayOfMonth'] = df.Date.dt.day
df['DaySuffix'] = df.Date.dt.day.astype(str) + df.Date.dt.day.map(lambda x: 'th' if 11<=x<=13 else {1:'st',2:'nd',3:'rd'}.get(x%10, 'th'))
df["DayName"] = df.Date.dt.day_name()
df["DayOfWeek"] = df.Date.dt.weekday.map(pd.Series('2,3,4,5,6,7,1'.split(',')))
#df["DayOfWeekInMonth"] = df.Date.map(lambda x: idx[0] for if y == x.day idx, y in np.ndenumerate(calendar.monthcalendar(x.year,x.month)))
#df["DayOfWeekInMonth"] = 
#df["Week"] = df.Date.dt.weekofyear
#df['MonthName'] = df.Date.dt.month.map(lambda x: c.month_name(x))
df['MonthName'] = df.Date.dt.month.map(pd.Series('NONE,January,February,March,April,May,June,July,August,September,October,November,December'.split(',')))
#df['MonthName'] = df.Date.dt.month
#df["Quarter"] = df.Date.dt.quarter
df["Year"] = df.Date.dt.year

df.head(60)

,Date,DateCK,FormattedDate,DayOfMonth,DaySuffix,DayName,DayOfWeek,MonthName,Year
0,2022-03-01,20220301,03/01/2022,1,1st,Tuesday,3,March,2022
1,2022-03-02,20220302,03/02/2022,2,2nd,Wednesday,4,March,2022
2,2022-03-03,20220303,03/03/2022,3,3rd,Thursday,5,March,2022
3,2022-03-04,20220304,03/04/2022,4,4th,Friday,6,March,2022
4,2022-03-05,20220305,03/05/2022,5,5th,Saturday,7,March,2022
5,2022-03-06,20220306,03/06/2022,6,6th,Sunday,1,March,2022
6,2022-03-07,20220307,03/07/2022,7,7th,Monday,2,March,2022
7,2022-03-08,20220308,03/08/2022,8,8th,Tuesday,3,March,2022
8,2022-03-09,20220309,03/09/2022,9,9th,Wednesday,4,March,2022
9,2022-03-10,20220310,03/10/2022,10,10th,Thursday,5,March,2022
10,2022-03-11,20220311,03/11/2022,11,11th,Friday,6,March,2022
11,2022-03-12,20220312,03/12/2022,12,12th,Saturday,7,March,2022
12,2022-03-13,20220313,03/13/2022,13,13th,Sunday,1,March,2022
13,2022-03-14,20220314,03/14/2022,14,14th,Monday,2,March,2022
14,2022-03-15,20220315,03/15/2022,15,15th,Tuesday,3,March,2022
15,2022-03-16,20220316,03/16/2022,16,16th,Wednesday,4,March,2022
16,2022-03-17,20220317,03/17/2022,17,17th,Thursday,5,March,2022
17,2022-03-18,20220318,03/18/2022,18,18th,Friday,6,March,2022
18,2022-03-19,20220319,03/19/2022,19,19th,Saturday,7,March,2022
19,2022-03-20,20220320,03/20/2022,20,20th,Sunday,1,March,2022
20,2022-03-21,20220321,03/21/2022,21,21st,Monday,2,March,2022
21,2022-03-22,20220322,03/22/2022,22,22nd,Tuesday,3,March,2022
22,2022-03-23,20220323,03/23/2022,23,23rd,Wednesday,4,March,2022
23,2022-03-24,20220324,03/24/2022,24,24th,Thursday,5,March,2022
24,2022-03-25,20220325,03/25/2022,25,25th,Friday,6,March,2022
25,2022-03-26,20220326,03/26/2022,26,26th,Saturday,7,March,2022
26,2022-03-27,20220327,03/27/2022,27,27th,Sunday,1,March,2022
27,2022-03-28,20220328,03/28/2022,28,28th,Monday,2,March,2022
28,2022-03-29,20220329,03/29/2022,29,29th,Tuesday,3,March,2022
29,2022-03-30,20220330,03/30/2022,30,30th,Wednesday,4,March,2022
30,2022-03-31,20220331,03/31/2022,31,31st,Thursday,5,March,2022
31,2022-04-01,20220401,04/01/2022,1,1st,Friday,6,April,2022
32,2022-04-02,20220402,04/02/2022,2,2nd,Saturday,7,April,2022
33,2022-04-03,20220403,04/03/2022,3,3rd,Sunday,1,April,2022
34,2022-04-04,20220404,04/04/2022,4,4th,Monday,2,April,2022
35,2022-04-05,20220405,04/05/2022,5,5th,Tuesday,3,April,2022
36,2022-04-06,20220406,04/06/2022,6,6th,Wednesday,4,April,2022
37,2022-04-07,20220407,04/07/2022,7,7th,Thursday,5,April,2022
38,2022-04-08,20220408,04/08/2022,8,8th,Friday,6,April,2022
39,2022-04-09,20220409,04/09/2022,9,9th,Saturday,7,April,2022
40,2022-04-10,20220410,04/10/2022,10,10th,Sunday,1,April,2022
41,2022-04-11,20220411,04/11/2022,11,11th,Monday,2,April,2022
42,2022-04-12,20220412,04/12/2022,12,12th,Tuesday,3,April,2022
43,2022-04-13,20220413,04/13/2022,13,13th,Wednesday,4,April,2022
44,2022-04-14,20220414,04/14/2022,14,14th,Thursday,5,April,2022
45,2022-04-15,20220415,04/15/2022,15,15th,Friday,6,April,2022
46,2022-04-16,20220416,04/16/2022,16,16th,Saturday,7,April,2022
47,2022-04-17,20220417,04/17/2022,17,17th,Sunday,1,April,2022
48,2022-04-18,20220418,04/18/2022,18,18th,Monday,2,April,2022
49,2022-04-19,20220419,04/19/2022,19,19th,Tuesday,3,April,2022
50,2022-04-20,20220420,04/20/2022,20,20th,Wednesday,4,April,2022
51,2022-04-21,20220421,04/21/2022,21,21st,Thursday,5,April,2022
52,2022-04-22,20220422,04/22/2022,22,22nd,Friday,6,April,2022
53,2022-04-23,20220423,04/23/2022,23,23rd,Saturday,7,April,2022
54,2022-04-24,20220424,04/24/2022,24,24th,Sunday,1,April,2022
55,2022-04-25,20220425,04/25/2022,25,25th,Monday,2,April,2022
56,2022-04-26,20220426,04/26/2022,26,26th,Tuesday,3,April,2022
57,2022-04-27,20220427,04/27/2022,27,27th,Wednesday,4,April,2022
58,2022-04-28,20220428,04/28/2022,28,28th,Thursday,5,April,2022
59,2022-04-29,20220429,04/29/2022,29,29th,Friday,6,April,2022

In [126]:
from datetime import datetime
import numpy as np


#for i, y in np.ndenumerate(calendar.monthcalendar(datetime.now().year,datetime.now().month)):  
    #if (y == 29):
            #print(i[0])
            #break


#len([1 for i in calendar.monthcalendar(datetime.now().year,datetime.now().month) if i[x.weekday] != 0])

print(calendar.monthcalendar(datetime.now().year,datetime.now().month))

[[0, 0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26], [27, 28, 29, 30, 31, 0, 0]]

In [199]:
newdf = df.sort_values(["Year","MonthName","DayName"], ascending=True).groupby(["DayOfMonth"]).cumcount() + 1

newdf.head(20)

31    1
38    1
45    1
52    1
59    1
34    1
41    1
48    1
55    1
32    1
39    1
46    1
53    1
60    1
33    1
40    1
47    1
54    1
37    1
44    1
dtype: int64